apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-backend
  template:
    metadata:
      labels:
        app: cicd-backend
    spec:
      containers:
        - name: cicd-backend
          image: bhanuteja110/cicd-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://192.168.49.2:3306/tutordb?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Kitler@110
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT
              value: "0"
            - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
              value: "30000"
            - name: SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT
              value: "5000"
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "sleep 10"]

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-backend-service
spec:
  type: NodePort
  selector:
    app: cicd-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
