apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-frontend
  template:
    metadata:
      labels:
        app: cicd-frontend
    spec:
      containers:
        - name: cicd-frontend
          image: bhanuteja110/cicd-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-frontend-service
spec:
  type: NodePort
  selector:
    app: cicd-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30073
