apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-ingress
spec:
  rules:
    - host: frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cicd-frontend-service
                port:
                  number: 80

    - host: backend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cicd-backend-service
                port:
                  number: 8080
